export const CALCULATE_MATH_OPERATION = "CALCULATE_MATH_OPERATION";
export const SET_LOADING = "SET_LOADING";
export const CANCEL_LOADING = "CANCEL_LOADING";
export const CLEAR_CALCULATOR_DATA = "CLEAR_CALCULATOR_DATA";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
